### ISSUE TITLE
Failed maven build

### ISSUE THREAD

**Issue by usadamasa** [tkuenzel/pmccabe-plugin#1]
Hello!

I was unable unfortunately When I try to build your plug-in :(
I'm think pom.xml is old , and I have gone fix ?

``` bash
$ mvn package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for jenkinsci.plugins.pmccabe:pmccabe:0.3: Failure to find org.jenkins-ci.plugins:plugin:pom:1.410 in http://maven.glassfish.org/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of m.g.o-public has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 3, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project jenkinsci.plugins.pmccabe:pmccabe:0.3 (/Users/masaru-uchida/Desktop/pmccabe-plugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for jenkinsci.plugins.pmccabe:pmccabe:0.3: Failure to find org.jenkins-ci.plugins:plugin:pom:1.410 in http://maven.glassfish.org/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of m.g.o-public has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 3, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

```

thanks.

**Comment by mattplees** [comment]
Hi. I have some issues on this as well. I got this far after having to update the version in the pop file from 1.410 to 2.2. 
This now looks like compilation issues due to a later version of jenkins. Any ideas how we can fix it?

$ mvn package -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Jenkins PMcCabe Plug-in 0.3
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-hpi-plugin:1.115:validate (default-validate) @ pmccabe ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:display-info (display-info) @ pmccabe ---
[INFO] Maven Version: 3.0.5
[INFO] JDK Version: 1.7.0_101 normalized as: 1.7.0-101
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 3.19.0-59-generic
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (display-info) @ pmccabe ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.2.201409121644:prepare-agent (default) @ pmccabe ---
[INFO] argLine set to -javaagent:/home/user/.m2/repository/org/jacoco/org.jacoco.agent/0.7.2.201409121644/org.jacoco.agent-0.7.2.201409121644-runtime.jar=destfile=/home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/jacoco.exec,excludes=**/Messages.class
[INFO]
[INFO] --- maven-localizer-plugin:1.23:generate (default) @ pmccabe ---
[INFO]
[INFO] >>> maven-javadoc-plugin:2.10.1:javadoc (default) @ pmccabe >>>
[INFO]
[INFO] --- maven-hpi-plugin:1.115:validate (default-validate) @ pmccabe ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:display-info (display-info) @ pmccabe ---
[INFO] Maven Version: 3.0.5
[INFO] JDK Version: 1.7.0_101 normalized as: 1.7.0-101
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 3.19.0-59-generic
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (display-info) @ pmccabe ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.2.201409121644:prepare-agent (default) @ pmccabe ---
[INFO] argLine set to -javaagent:/home/user/.m2/repository/org/jacoco/org.jacoco.agent/0.7.2.201409121644/org.jacoco.agent-0.7.2.201409121644-runtime.jar=destfile=/home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/jacoco.exec,excludes=**/Messages.class
[INFO]
[INFO] --- maven-localizer-plugin:1.23:generate (default) @ pmccabe ---
[INFO]
[INFO] <<< maven-javadoc-plugin:2.10.1:javadoc (default) @ pmccabe <<<
[INFO]
[INFO] --- maven-javadoc-plugin:2.10.1:javadoc (default) @ pmccabe ---
[INFO]
Loading source files for package jenkinsci.plugins.pmccabe...
Loading source files for package jenkinsci.plugins.pmccabe.utils...
Loading source files for package jenkinsci.plugins.pmccabe.util...
Constructing Javadoc information...
Standard Doclet version 1.7.0_101
Building tree for all the packages and classes...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/PmcabeSummary.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/PmccabeAction.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/PmccabeChartBuilder.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/PmccabeProjectAction.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/PmccabeRecoderDescriptor.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/PmccabeRecorder.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/utils/PmccabeFileParser.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/utils/PmccabeFunctionSummary.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/utils/PmccabeReport.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/util/Messages.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/overview-frame.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/package-frame.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/package-summary.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/package-tree.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/util/package-frame.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/util/package-summary.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/util/package-tree.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/utils/package-frame.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/utils/package-summary.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/utils/package-tree.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/constant-values.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/serialized-form.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/class-use/PmccabeRecoderDescriptor.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/class-use/PmccabeProjectAction.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/class-use/PmccabeChartBuilder.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/class-use/PmcabeSummary.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/class-use/PmccabeAction.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/class-use/PmccabeRecorder.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/utils/class-use/PmccabeReport.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/utils/class-use/PmccabeFunctionSummary.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/utils/class-use/PmccabeFileParser.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/util/class-use/Messages.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/package-use.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/util/package-use.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/jenkinsci/plugins/pmccabe/utils/package-use.html...
Building index for all the packages and classes...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/overview-tree.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/index-all.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/deprecated-list.html...
Building index for all classes...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/allclasses-frame.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/allclasses-noframe.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/index.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/overview-summary.html...
Generating /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/site/apidocs/help-doc.html...
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ pmccabe ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 13 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ pmccabe ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 10 source files to /home/user/code/pmccabe_plugin/pmccabe-plugin-master/target/classes
[INFO] /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/PmccabeRecorder.java: /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/PmccabeRecorder.java uses unchecked or unsafe operations.
[INFO] /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/PmccabeRecorder.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/PmccabeChartBuilder.java:[115,51] reference to NumberOnlyBuildLabel is ambiguous, both constructor NumberOnlyBuildLabel(hudson.model.Run<?,?>) in hudson.util.ChartUtil.NumberOnlyBuildLabel and constructor NumberOnlyBuildLabel(hudson.model.AbstractBuild) in hudson.util.ChartUtil.NumberOnlyBuildLabel match
[ERROR] /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/PmccabeChartBuilder.java:[133,51] reference to NumberOnlyBuildLabel is ambiguous, both constructor NumberOnlyBuildLabel(hudson.model.Run<?,?>) in hudson.util.ChartUtil.NumberOnlyBuildLabel and constructor NumberOnlyBuildLabel(hudson.model.AbstractBuild) in hudson.util.ChartUtil.NumberOnlyBuildLabel match
[ERROR] /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/PmccabeChartBuilder.java:[151,51] reference to NumberOnlyBuildLabel is ambiguous, both constructor NumberOnlyBuildLabel(hudson.model.Run<?,?>) in hudson.util.ChartUtil.NumberOnlyBuildLabel and constructor NumberOnlyBuildLabel(hudson.model.AbstractBuild) in hudson.util.ChartUtil.NumberOnlyBuildLabel match
[ERROR] /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/utils/PmccabeFileParser.java:[16,8] jenkinsci.plugins.pmccabe.utils.PmccabeFileParser is not abstract and does not override abstract method checkRoles(org.jenkinsci.remoting.RoleChecker) in org.jenkinsci.remoting.RoleSensitive
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.446s
[INFO] Finished at: Wed May 11 18:49:46 BST 2016
[INFO] Final Memory: 33M/105M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project pmccabe: Compilation failure: Compilation failure:
[ERROR] /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/PmccabeChartBuilder.java:[115,51] reference to NumberOnlyBuildLabel is ambiguous, both constructor NumberOnlyBuildLabel(hudson.model.Run<?,?>) in hudson.util.ChartUtil.NumberOnlyBuildLabel and constructor NumberOnlyBuildLabel(hudson.model.AbstractBuild) in hudson.util.ChartUtil.NumberOnlyBuildLabel match
[ERROR] /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/PmccabeChartBuilder.java:[133,51] reference to NumberOnlyBuildLabel is ambiguous, both constructor NumberOnlyBuildLabel(hudson.model.Run<?,?>) in hudson.util.ChartUtil.NumberOnlyBuildLabel and constructor NumberOnlyBuildLabel(hudson.model.AbstractBuild) in hudson.util.ChartUtil.NumberOnlyBuildLabel match
[ERROR] /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/PmccabeChartBuilder.java:[151,51] reference to NumberOnlyBuildLabel is ambiguous, both constructor NumberOnlyBuildLabel(hudson.model.Run<?,?>) in hudson.util.ChartUtil.NumberOnlyBuildLabel and constructor NumberOnlyBuildLabel(hudson.model.AbstractBuild) in hudson.util.ChartUtil.NumberOnlyBuildLabel match
[ERROR] /home/user/code/pmccabe_plugin/pmccabe-plugin-master/src/main/java/jenkinsci/plugins/pmccabe/utils/PmccabeFileParser.java:[16,8] jenkinsci.plugins.pmccabe.utils.PmccabeFileParser is not abstract and does not override abstract method checkRoles(org.jenkinsci.remoting.RoleChecker) in org.jenkinsci.remoting.RoleSensitive
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project pmccabe: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:911)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
